# TCL File Generated by Component Editor 19.1
# Tue Mar 17 07:12:15 JST 2020
# DO NOT MODIFY


# 
# avalon_sk6812rgbw "Avalon SK6812RGBW" v1.0
# Shunichi Yamamoto 2020.03.17.07:12:15
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_sk6812rgbw
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_sk6812rgbw
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Shunichi Yamamoto"
set_module_property DISPLAY_NAME "Avalon SK6812RGBW"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AVALON2SK6812RGBW
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon2sk6812rgbw.vhd VHDL PATH avalon2sk6812rgbw.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter LED_BIT_WIDTH INTEGER 32
set_parameter_property LED_BIT_WIDTH DEFAULT_VALUE 32
set_parameter_property LED_BIT_WIDTH DISPLAY_NAME LED_BIT_WIDTH
set_parameter_property LED_BIT_WIDTH TYPE INTEGER
set_parameter_property LED_BIT_WIDTH UNITS None
set_parameter_property LED_BIT_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LED_BIT_WIDTH HDL_PARAMETER true
add_parameter T0H INTEGER 30
set_parameter_property T0H DEFAULT_VALUE 30
set_parameter_property T0H DISPLAY_NAME T0H
set_parameter_property T0H TYPE INTEGER
set_parameter_property T0H UNITS None
set_parameter_property T0H ALLOWED_RANGES -2147483648:2147483647
set_parameter_property T0H HDL_PARAMETER true
add_parameter T1H INTEGER 60
set_parameter_property T1H DEFAULT_VALUE 60
set_parameter_property T1H DISPLAY_NAME T1H
set_parameter_property T1H TYPE INTEGER
set_parameter_property T1H UNITS None
set_parameter_property T1H ALLOWED_RANGES -2147483648:2147483647
set_parameter_property T1H HDL_PARAMETER true
add_parameter T0L INTEGER 90
set_parameter_property T0L DEFAULT_VALUE 90
set_parameter_property T0L DISPLAY_NAME T0L
set_parameter_property T0L TYPE INTEGER
set_parameter_property T0L UNITS None
set_parameter_property T0L ALLOWED_RANGES -2147483648:2147483647
set_parameter_property T0L HDL_PARAMETER true
add_parameter T1L INTEGER 60
set_parameter_property T1L DEFAULT_VALUE 60
set_parameter_property T1L DISPLAY_NAME T1L
set_parameter_property T1L TYPE INTEGER
set_parameter_property T1L UNITS None
set_parameter_property T1L ALLOWED_RANGES -2147483648:2147483647
set_parameter_property T1L HDL_PARAMETER true
add_parameter TRST INTEGER 80
set_parameter_property TRST DEFAULT_VALUE 80
set_parameter_property TRST DISPLAY_NAME TRST
set_parameter_property TRST TYPE INTEGER
set_parameter_property TRST UNITS None
set_parameter_property TRST ALLOWED_RANGES -2147483648:2147483647
set_parameter_property TRST HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset csi_reset_n reset_n Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset clock_reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_address address Input 4
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_writedata writedata Input 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point external_connection
# 
add_interface external_connection conduit end
set_interface_property external_connection associatedClock clock
set_interface_property external_connection associatedReset ""
set_interface_property external_connection ENABLED true
set_interface_property external_connection EXPORT_OF ""
set_interface_property external_connection PORT_NAME_MAP ""
set_interface_property external_connection CMSIS_SVD_VARIABLES ""
set_interface_property external_connection SVD_ADDRESS_GROUP ""

add_interface_port external_connection DOUT1 dout1 Output 1
add_interface_port external_connection DOUT2 dout2 Output 1

